# Generated by Django 3.1.5 on 2021-02-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210215_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniqloitem',
            options={'ordering': ['ClothesType', 'UNIQLOTitle']},
        ),
    ]
