# Generated by Django 3.1.5 on 2021-02-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20210215_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqloitem',
            name='SubImagesJSON',
            field=models.CharField(max_length=2000),
        ),
    ]
